version: '3.8'
services:
  api:
    build:
      context: ./Steps.Api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - appnet

  frontend:
    build:
      context: ./steps-ui
      args:
        REACT_APP_API_URL: http://homelab.io:5000
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
