apiVersion: v1
kind: PersistentVolume
metadata:
  name: steps-sqlite-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/steps/sqlite-data 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steps-sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi